import Footer from "@/sections/Footer";
import Header from "@/sections/Header";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetBrains_Mono = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800',]
})

export const metadata: Metadata = {
  title: "AI Riddle Generator - Brain Teasers Generated by AI",
  description: "Get challenging questions and answers with our AI-powered riddle generator",
  verification: {
    google: 'xXjJtQZBYvHXYRqToKKo30qSzTNchNmzZfILm5g11Qo',
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jetBrains_Mono.className} px-4 md:p-0 max-w-3xl mx-auto bg-[#d5d1ef]`}>
        <Header className="mb-20"/>
        <main>
        {children}
        </main>
        <Toaster />
        <Footer className="mt-16"/>
      </body>
    </html>
  );
}